# Site settings
title: TEMPLATESTUD.IO
email: alex@templatestud.io
url: https://templatestud.io
description: "Hello, I'm Alex Wu and I'm a Marketing Web Developer"
skills: "I build technical solutions to help marketers make more money"
baseurl: ""


# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
collections:
   my_templates:
    output: true
    permalink: /:categories/:title/
   my_emails:
    output: true
    permalink: /:categories/:title/


# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1

#disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Outputting
permalink:     /:title.html
paginate: 5
paginate_path: /blog/:num/
timezone:      null

quiet:    false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
      layout: "blog-post"
      categories: "blog"
      tags: ""
      img: "image.jpg"
      alt: "image"
      featured_image: "image.jpg"
      lead-text: "Lead Text"
  -
    scope:
      path: ""
      type: "my_templates"
    values:
      layout: "inner"

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []


# Footer settings
footer:
  copyright: Templatestud.io



include: ['_pages']
